### ISSUE TITLE
Images are mixed up.

### ISSUE THREAD

**Issue by Nailik** [graphefruit/Beanconqueror#568]
There are multiple issues with the images:

- when i scroll a long list of beans (only 38) then sometimes i see images for beans where i didn't add any image
- sometimes i add an image to a bean and it gets added to another one as well (overrides current image) also when i then update on the other bean the image to the correct one the first one gets changed as well
    - looks like two beans share the same image ?

**Comment by graphefruit** [comment]
Hello @Nailik,
thanks for reporting this issue.
Thats very strange, about more then one year ago this issue was reported and got "resolved".
May I ask you, how long do you use Beanconqueror already and when did you added those beans?
If they are old, that could be an issue, if they are new, this issue (should be resolved) but seems like arent?

Do you copy beans and change the information, or do you realy press "add" and then add the images?

Can you please send me your exported .JSON and tell me those beans which share the same image? - info@beanconqueror.com
Thanks
Lars

**Comment by Nailik** [comment]
I am using the App Since Nov. 2021 but the issue happens with Beans i added March 2023 and Jun. 2023 (Today)

**Comment by graphefruit** [comment]
Could you please give me the information about your workflow? 
Did you add them with "+" or did you repeat an older one?

**Comment by Nailik** [comment]
Today i added images to beans because last time the issue wasn't fixed ;) 
I added new beans via the + Button and after some beans the issue appeard.

**Comment by graphefruit** [comment]
@Nailik - thanks for the mail and thanks for your digging.
Thats so! Super strange.
Can you delete the image on "both" beans. Close the app completely, Open up, add one image on one bean, and see if the issue exists still?

This is a reference issue, but I still don't understand how this reference is coming into place, this was the issue back in the times but the reporting users told me that it has been fixed, therefore its strange its here again... 
I'll check the code anyhow

**Comment by graphefruit** [comment]
What I still could think off that - I know that isn't a good solution:
Maybe a restart of the phone would help after adding a bean, before adding another one - just to make sure.

The file api of android has gone many restrictions and changes, and maybe the file-system is reporting "strange things".
I also had back in the days some issues with reading/writing files, when they existed before

**Comment by Nailik** [comment]
The issue was solved my deleting the image from both beans. On the second bean however it was difficult because the delete button was almost impossible to see and click. (Probably because the image could not be shown because it was already deleted).
Afterwards I could add the image to both (without closing/reopening the app) and the issue was fixed

**Comment by Nailik** [comment]
So why is this still json file based and not using a database? 
Is there no library for cordova that supports a database?

**Comment by graphefruit** [comment]
> So why is this still json file based and not using a database? Is there no library for cordova that supports a database?

Beanconqueror uses an IndexDB in behind.
.JSON-Files are used as export/import, in the next update the .JSON-Files will be cut in chunk-sizes into a .zip file.

**Comment by graphefruit** [comment]
I think we finally found this issue.
@RagingCactus helped to make it work, I'll cover this topic in the next release, and if needed open up a new ticket then please.

**Comment by RagingCactus** [comment]
See #835 and #833
